### ISSUE TITLE
un-release-zalgo

### ISSUE THREAD

**Issue by jimmywarting** [novemberborn/release-zalgo#14]
This package is soo confusing and over complicated that I had a hart time to wrap my head around it. Both here and in the `package-hash` package

- This never got any stars since it was first released. 
- Hardly anyone is [depending](https://www.npmjs.com/browse/depended/release-zalgo) on it. Most downloads comes from your own `package-hash` package
- Typing (either via jsdoc, checkjs, d.ts or typescript) provides better information if something is sync or async and with what arguments it takes and what it returns. This just turns anything into `any`
- nobody ever created any issues (b/c nobody else is using it?)

I'm only wondering if you could consider 
- deprecate the npm package
- delete or archive this repo
- or mark it as legacy
- update `package-hash` so it don't depend on `release-zalgo`

**Comment by novemberborn** [comment]
PR welcome on `package-hash`.
